/*
 *  Source machine generated by GadToolsBox V2.0b
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : Kriton Kyrimis & Diego Casorran
 */

#define GetString( g )      ((( struct StringInfo * )g->SpecialInfo )->Buffer  )
#define GetNumber( g )      ((( struct StringInfo * )g->SpecialInfo )->LongInt )

#define GD_savegad                             0
#define GD_usegad                              1
#define GD_cancelgad                           2
#define GD_translateslash                      3
#define GD_membuf                              4
#define GD_blocks                              5
#define GD_case                                6
#define GD_suppress                            7
#define GD_amigawildcard                       8
#define GD_noflush                             9
#define GD_ignoreenv                           10
#define GD_networking                          11
#define GD_enforcerhit                         12
#define GD_profilemethod                       13
#define GD_stackusage                          14
#define GD_mufs                                15
#define GD_advanced                            16
#define GD_watchAvailMem                       17
#define GD_catchfailedallocs                   18
#define GD_killappallocerr                     19
#define GD_blacklist                           20

#define GDX_savegad                            0
#define GDX_usegad                             1
#define GDX_cancelgad                          2
#define GDX_translateslash                     3
#define GDX_membuf                             4
#define GDX_blocks                             5
#define GDX_case                               6
#define GDX_suppress                           7
#define GDX_amigawildcard                      8
#define GDX_noflush                            9
#define GDX_ignoreenv                          10
#define GDX_networking                         11
#define GDX_enforcerhit                        12
#define GDX_profilemethod                      13
#define GDX_stackusage                         14
#define GDX_mufs                               15
#define GDX_advanced                           16
#define GDX_watchAvailMem                      17
#define GDX_catchfailedallocs                  18
#define GDX_killappallocerr                    19
#define GDX_blacklist                          20

#define ixprefs_CNT 21

extern struct IntuitionBase *IntuitionBase;
extern struct Library       *GadToolsBase;

extern struct Screen        *Scr;
extern UBYTE                 *PubScreenName;
extern APTR                  VisualInfo;
extern struct Window        *ixprefsWnd;
extern struct Gadget        *ixprefsGList;
extern struct Menu          *ixprefsMenus;
extern struct IntuiMessage   ixprefsMsg;
extern struct Gadget        *ixprefsGadgets[21];
extern UWORD                 ixprefsLeft;
extern UWORD                 ixprefsTop;
extern UWORD                 ixprefsWidth;
extern UWORD                 ixprefsHeight;
extern UBYTE                *ixprefsWdt;
extern struct TextAttr      *Font, Attr;
extern UWORD                 FontX, FontY;
extern UWORD                 OffX, OffY;
extern struct TextFont      *ixprefsFont;
extern struct GfxBase       *GfxBase;
extern UBYTE                *networking0Labels[];
extern UBYTE                *profilemethod0Labels[];
extern struct NewMenu        ixprefsNewMenu[];
extern UWORD                 ixprefsGTypes[];
extern struct NewGadget      ixprefsNGad[];
extern ULONG                 ixprefsGTags[];

extern int savegadClicked( void );
extern int usegadClicked( void );
extern int cancelgadClicked( void );
extern int translateslashClicked( void );
extern int membufClicked( void );
extern int blocksClicked( void );
extern int caseClicked( void );
extern int suppressClicked( void );
extern int amigawildcardClicked( void );
extern int noflushClicked( void );
extern int ignoreenvClicked( void );
extern int networkingClicked( void );
extern int enforcerhitClicked( void );
extern int profilemethodClicked( void );
extern int stackusageClicked( void );
extern int mufsClicked( void );
extern int advancedClicked( void );
extern int watchAvailMemClicked( void );
extern int catchfailedallocsClicked( void );
extern int killappallocerrClicked( void );
extern int blacklistClicked( void );
extern int ixprefssave( void );
extern int ixprefsuse( void );
extern int ixprefsabout( void );
extern int ixprefsquit( void );
extern int ixprefsreset( void );
extern int ixprefslast( void );
extern int ixprefsrestore( void );

extern int SetupScreen( void );
extern void CloseDownScreen( void );
extern int HandleixprefsIDCMP( void );
extern int ixprefsCloseWindow();
extern int OpenixprefsWindow( void );
extern void CloseixprefsWindow( void );
